import { Controller } from "@hotwired/stimulus"
export default class extends Controller {
  static targets = ["badge", "item", "search"]

  connect() {
    this.openCustomerId = window.OPEN_CUSTOMER_ID || null
    this.unreadCounts = new Map()
    this.messageUpdateTimers = {}

    // Observe only DOM insertions inside sidebar
    this.observer = new MutationObserver(mutations => {
      mutations.forEach(m => this.processMutation(m))
    })

    this.observer.observe(this.element, { childList: true, subtree: true })
  }

  disconnect() {
    if (this.observer) this.observer.disconnect()
  }

  filter(event) {
    const query = event.target.value.toLowerCase().trim()

    this.itemTargets.forEach(item => {
      const name = item.dataset.customerName?.toLowerCase() || ""
      const number = item.dataset.customerNumber || ""
      const matches = name.includes(query) || number.includes(query)
      item.classList.toggle("hidden", !matches)
    })
  }

  /** When a chat row is clicked */
  openCustomer(event) {
    const el = event.currentTarget
    const customerId = Number(el.dataset.customerId)
    if (!customerId) return

    this.openCustomerId = customerId
    window.OPEN_CUSTOMER_ID = customerId

    this.setActiveCustomer(customerId)
    this.setUnread(customerId, 0)

    // close sidebar on mobile after selecting a customer
    const mobileSidebar = this.element.closest("[data-controller~='mobile-sidebar']")
    if (mobileSidebar) {
      const ctrl = this.application.getControllerForElementAndIdentifier(
        mobileSidebar,
        "mobile-sidebar"
      )
      ctrl?.close()
    }
  }

  setActiveCustomer(customerId) {
    // Remove active state from all
    this.element.querySelectorAll(".customers-sidebar-link").forEach(link => {
      link.classList.remove("bg-[rgb(var(--hover))]")
      const indicator = link.querySelector(".customers-active-indicator")
      if (indicator) indicator.classList.add("opacity-0")
    })

    // Add active state to clicked
    const activeLink = this.element.querySelector(`#customer-link-${customerId}`)
    if (!activeLink) return
    activeLink.classList.add("bg-[rgb(var(--hover))]")
    const activeIndicator = activeLink.querySelector(".customers-active-indicator")
    if (activeIndicator) activeIndicator.classList.remove("opacity-0")
  }

  /** Process mutation and detect last_message updates */
  processMutation(mutation) {
    // ignore mutations generated by updating unread badge itself
    if (mutation.target.closest(".unread-badge")) return

    mutation.addedNodes?.forEach(node => {
      if (!(node instanceof Element)) return

      if (this.isLastMessageNode(node)) this.handleLastMessage(node)

      node.querySelectorAll?.("[id^='last_message_customer_']")
        .forEach(n => this.handleLastMessage(n))
    })
  }

  /** Check if element is the last_message node */
  isLastMessageNode(node) {
    return node.id?.startsWith("last_message_customer_")
  }

  /** Collapse multiple updates into one unread increment */
  handleLastMessage(node) {
    const match = node.id.match(/^last_message_customer_(\d+)$/)
    if (!match) return
    const customerId = Number(match[1])
    // skip if debounce active
    if (this.messageUpdateTimers[customerId]) return

    this.messageUpdateTimers[customerId] = setTimeout(() => {
      delete this.messageUpdateTimers[customerId]

      if (this.openCustomerId === customerId) {
        this.setUnread(customerId, 0)
      } else {
        const prev = this.unreadCounts.get(customerId) || 0
        this.setUnread(customerId, prev + 1)
        this.playNotificationSound()
      }
    }, 80)
  }

  /** Update unread badge */
  setUnread(customerId, value) {
    const badge = this.element.querySelector(`.unread-badge[data-customer-id="${customerId}"]`)

    if (!badge) return
    if (value > 0) {
      this.unreadCounts.set(customerId, value)
      badge.textContent = value
      badge.classList.remove("hidden")
      badge.classList.add("inline-flex")
    } else {
      this.unreadCounts.delete(customerId)
      badge.textContent = "0"
      badge.classList.add("hidden")
      badge.classList.remove("inline-flex")
    }
  }

  playNotificationSound() {
    const el = document.querySelector("[data-controller~='notification-sound']")
    if (!el) return
    const ctrl = this.application.getControllerForElementAndIdentifier(el, "notification-sound")
    ctrl?.play()
  }
}
