import { Controller } from "@hotwired/stimulus"
export default class extends Controller {
  static targets = ["badge", "item", "search"]

  connect() {
    this.openCustomerId = this.getOpenCustomerId()
    this.unreadCounts = new Map()
    this.messageUpdateTimers = {}

    if (this.openCustomerId) {
      this.setActiveCustomer(Number(this.openCustomerId))
    }

    this.observer = new MutationObserver(mutations => {
      mutations.forEach(m => this.processMutation(m))
    })

    this.observer.observe(this.element, {
      childList: true,
      subtree: true,
      characterData: true 
    })

  }

  disconnect() {
    if (this.observer) this.observer.disconnect()
  }

  getOpenCustomerId() {
    const frame = document.getElementById("chat_frame")
    const id = frame?.dataset?.openCustomerId
    return id ? Number(id) : null
  }

  filter(event) {
    const query = event.target.value.toLowerCase().trim()

    this.itemTargets.forEach(item => {
      const name = item.dataset.customerName?.toLowerCase() || ""
      const number = item.dataset.customerNumber || ""
      const matches = name.includes(query) || number.includes(query)
      item.classList.toggle("hidden", !matches)
    })
  }

  /** When a chat row is clicked */
  openCustomer(event) {
    const el = event.currentTarget
    const customerId = Number(el.dataset.customerId)
    if (!customerId) return

    this.openCustomerId = customerId
    window.OPEN_CUSTOMER_ID = customerId

    this.setActiveCustomer(customerId)
    this.setUnread(customerId, 0)

    // close sidebar on mobile after selecting a customer
    const mobileSidebar = this.element.closest("[data-controller~='mobile-sidebar']")
    if (mobileSidebar) {
      const ctrl = this.application.getControllerForElementAndIdentifier(
        mobileSidebar,
        "mobile-sidebar"
      )
      ctrl?.close()
    }
  }

  setActiveCustomer(customerId) {
    // Remove active state from all
    this.element.querySelectorAll(".customers-sidebar-link").forEach(link => {
      link.classList.remove("bg-[rgb(var(--hover))]")
      const indicator = link.querySelector(".customers-active-indicator")
      if (indicator) indicator.classList.add("opacity-0")
    })

    // Add active state to clicked
    const activeLink = this.element.querySelector(`#customer-link-${customerId}`)
    if (!activeLink) return
    activeLink.classList.add("bg-[rgb(var(--hover))]")
    const activeIndicator = activeLink.querySelector(".customers-active-indicator")
    if (activeIndicator) activeIndicator.classList.remove("opacity-0")
  }

  /** Process mutation and detect last_message updates */
  processMutation(mutation) {
    // ignore mutations generated by updating unread badge itself
    if (mutation.target.closest?.(".unread-badge")) return

    // Case A: last_message text updated (real new msg)
    // This happens when turbo updates the existing element text.
    if (mutation.type === "characterData") {
      const el = mutation.target.parentElement
      if (el && this.isLastMessageNode(el)) {
        this.handleLastMessage(el)
      }
      return
    }

    //  Case B: existing last_message element updated by replacing inner HTML
    if (mutation.type === "childList" && mutation.target instanceof Element) {
      if (this.isLastMessageNode(mutation.target)) {
        // If node already existed and its children changed -> treat as update
        // But ignore when it is inserted first time (handled below)
        if (!mutation.addedNodes?.length) {
          this.handleLastMessage(mutation.target)
        }
      }
    }

    // IMPORTANT: Ignore addedNodes for last_message elements
    // because infinite scroll append inserts them and would create fake unread counts.
    mutation.addedNodes?.forEach(node => {
      if (!(node instanceof Element)) return
      // If pagination appended nodes, do NOT treat them as "new message"
      // so we skip handleLastMessage on added nodes.
      // (Still allow other logic to continue if you want.)
    })
  }

  /** Check if element is the last_message node */
  isLastMessageNode(node) {
    return node.id?.startsWith("last_message_customer_")
  }

  /** Collapse multiple updates into one unread increment */
  handleLastMessage(node) {
    const match = node.id.match(/^last_message_customer_(\d+)$/)
    if (!match) return
    const customerId = Number(match[1])
    // skip if debounce active
    if (this.messageUpdateTimers[customerId]) return

    this.messageUpdateTimers[customerId] = setTimeout(() => {
      delete this.messageUpdateTimers[customerId]

      if (this.openCustomerId === customerId) {
        this.setUnread(customerId, 0)
        this.markReadInDb(customerId)
      } else {
        const count = Number(node.querySelector('[data-unread-count]')?.dataset.unreadCount || 0)
        this.setUnread(customerId, count)
        this.playNotificationSound()
      }
    }, 80)
  }

  /** Update unread badge */
  setUnread(customerId, value) {
    const badge = this.element.querySelector(`.unread-badge[data-customer-id="${customerId}"]`)

    if (!badge) return
    if (value > 0) {
      this.unreadCounts.set(customerId, value)
      badge.textContent = value
      badge.classList.remove("hidden")
      badge.classList.add("inline-flex")
    } else {
      this.unreadCounts.delete(customerId)
      badge.textContent = "0"
      badge.classList.add("hidden")
      badge.classList.remove("inline-flex")
    }
  }

  markReadInDb(customerId) {
    const token = document.querySelector("meta[name=csrf-token]")?.content
    if (!token) return

    fetch(`/chats/${customerId}/mark_read`, {
      method: "POST",
      headers: {
        "X-CSRF-Token": token,
        "Accept": "application/json"
      }
    }).catch(() => {})
  }


  playNotificationSound() {
    const el = document.querySelector("[data-controller~='notification-sound']")
    if (!el) return
    const ctrl = this.application.getControllerForElementAndIdentifier(el, "notification-sound")
    ctrl?.play()
  }
}
